# These are supported funding model platforms

ko_fi: # Replace with your Ko-fi username
custom: ["https://paypal.me/yafacs", "https://buymeacoffee.com/YOUR_USERNAME"]

# Alternative options you can uncomment and configure:
# open_collective: # Replace with your Open Collective username
# liberapay: # Replace with your Liberapay username
# patreon: # Replace with your Patreon username