[package]
name = "unified-sdk-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# Test the unified SDK
agents-sdk = { path = "../../crates/agents-sdk", features = ["full"] }
agents-core = { path = "../../crates/agents-core" }
async-trait = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
dotenv = "0.15.0"